services:
  mongo:
    image: mongo:latest
    ports:
      - '127.0.0.1:4080:27017'
  app:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_DB=true # Add line here
    ports:
      - '8080:8080'